
language: csharp
dist: xenial
mono: none
dotnet: 3.1.201
install:
- dotnet restore ./src/R.BooBus.sln
script:
- dotnet build /p:Version=1.0.1 --configuration Release ./src/R.BooBus.sln
- dotnet test ./src/R.BooBus.Tests/R.BooBus.Tests.csproj
