
language: csharp
dist: xenial
mono: none
dotnet: 3.1.201
install:
- dotnet restore ./src/R.BooBus.sln
script:
- dotnet build --configuration Release ./src/R.BooBus.sln
- dotnet test ./src/R.BooBus.Tests/R.BooBus.Tests.csproj
- dotnet nuget push ./src/R.BooBus.AzureServiceBus/bin/Release/R.Boobus.AzureServiceBus.1.0.0.nupkg -k $PACKAGE_PUBLISH -s https://api.nuget.org/v3/index.json